### ISSUE TITLE
Ciliates incorrectly classifies as Ascomycota

### ISSUE THREAD

**Issue by brendanf** [TU-NHM/sh_matching_pub#18]
In `shs_out.txt` from `sh_matching_data_0_5.zip`, there are 5346 instances of genus Ciliophora within Fungi;Ascomycota;Leotiomycetes;Helotiales.  While it is true that there is a genus called Ciliophora in Helotiales, cross-referencing with the Unite webpage suggests that most if not all of these should actually be in phylum Ciliophora of kingdom Alveolata.

**Comment by kessya** [comment]
Thank you, @brendanf. We'll be updating the underlying databases soon.
