### ISSUE TITLE
uchime?

### ISSUE THREAD

**Issue by brendanf** [TU-NHM/sh_matching_pub#40]
I can see that the pipeline runs `usearch -uchime2` which generates `uchime_out.txt`, but it seems that this file is never used in any way.  In particular, `exclude_chims.py` says in its usage note that it excludes chimeras identified by uchime and vsearch, but it never accesses the uchime file.  Am I missing something?

**Comment by kessya** [comment]
You are correct - this uchime_out.txt file was created for testing purposes and never used fr filtering out any sequences because UCHIME tends to identify non-chimeric sequences as chimeras. I'll remove it from the code.

**Comment by brendanf** [comment]
Ok, thanks for the explanation!
