### ISSUE TITLE
Finding best matches with `usearch_global` - usage of UDB instead of FASTA

### ISSUE THREAD

**Issue by vmikk** [TU-NHM/sh_matching_pub#42]
Hello!

For the existing SH sequence dataset, creating the database index and sequence masking is a time-consuming step.
It is performed [here](https://github.com/TU-NHM/sh_matching_pub/blob/6307fbe6e28284925d65a790020af2489e5a6dfc/sh_matching_analysis/run_pipeline.sh#L231
): https://github.com/TU-NHM/sh_matching_pub/blob/6307fbe6e28284925d65a790020af2489e5a6dfc/sh_matching_analysis/run_pipeline.sh#L231

However, there is no need to run it for all SH-matching tasks.
It is possible to create the index beforehand and ship UDB file with (or instead) the database to improve the analysis speed.
E.g., to create the database we can use:
```
vsearch --makeudb_usearch sanger_refs_sh_full.fasta --output sanger_refs_sh_full.udb
```

Then,  `vsearch --usearch_global` could be used with `--db sanger_refs_sh_full.udb`  instead of `--db sanger_refs_sh_full.fasta`.

**Comment by kessya** [comment]
Support for UDB formatted db search added (see readme).
